### ISSUE TITLE
White screen when receiving malformed transaction request

### ISSUE THREAD

**Issue by arterialist** [OpenProduct/openmask-extension#13]
**Describe the bug**
If user connects to the web app through TonConnect v2 using OpenMask and the app tries to send a malformed transaction, the OpenMask's pop-up displays as a white window.

**To Reproduce**
1. Connect your OpenMask to the web app you control
2. Send a malformed transaction request (text in 'amount' field for example)
3. See error

**Expected behavior**
A message telling the user that there was some kind of error, and a response to the TonConnect SDK that indicates a transaction failure

**Screenshots**
![image](https://user-images.githubusercontent.com/37044735/215095281-1741d479-15e6-4a13-a712-cc96c6897e72.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 109.0.5414.74

**Comment by KuznetsovNikita** [comment]
Hello,

Thank you for the report.

The issue will fix in OpenMask version 0.16.2

https://github.com/OpenProduct/openmask-extension/compare/v0.16.1...v0.16.2
