### ISSUE TITLE
Ledger Support? 

### ISSUE THREAD

**Issue by isKONSTANTIN** [OpenProduct/openmask-extension#14]
## Issue Essence
Hi! I found that none of the wallets support Ledger. I have seen some solutions for simple transfer and viewing the balance in the browser, but they turned out to be not very convenient.

## Ready-made Solutions
I would really like to see Ledger support in various wallets, such as OpenMask, but so far the best option is [ton-cli](https://github.com/tonwhales/ton-cli). It is written in TypeScript, so there should be fewer problems with implementation. [Here](https://github.com/tonwhales/ton-cli/blob/master/src/commands/openLedger.ts) is the code for working with Ledger via USB.

## Some Problems
At the moment, there is a small error in the master branch related to the connection, but I fixed it: https://github.com/tonwhales/ton-cli/pull/2

## The Requirements Are Small : )
It will be already very cool if there is a simple possibility to connect, view the balance and send coins in the extension. Work with DEX I think you can add later, for sure is a very specific code.

**Comment by KuznetsovNikita** [comment]
The Ledger Support

https://github.com/OpenProduct/openmask-extension/compare/v0.17.6...v0.18.0

@isKONSTANTIN @ex3ndr @talkol
Could you please verify and test my app?

To get 0.18 application version, you may restart chrome or press `Update` button in Developer move page chrome://extensions/

**Comment by KuznetsovNikita** [comment]
@isKONSTANTIN The feature was released and available for everyone
