### ISSUE TITLE
Chrome extension return wrong boc after transaction signed

### ISSUE THREAD

**Issue by egorguscha** [OpenProduct/openmask-extension#19]
**Describe the bug**
In chrome extension after signing transaction i got an wrong boc. Tonkeeper had the same bug bot now it fixed.

**Expected behavior**
Correct boc

**Screenshots**
<img width="613" alt="image" src="https://github.com/OpenProduct/openmask-extension/assets/22044607/f3b87849-ab39-4256-8cb0-290e0438f147">

**Comment by devlbrian** [comment]
I am experiencing the same issue, too

**Comment by KuznetsovNikita** [comment]
Hello
Thank you for report an issues!
Should be work correctly on 0.20.3 version
