### ISSUE TITLE
BIG BUG! 

### ISSUE THREAD

**Issue by wozuizuilike** [OpenProduct/openmask-extension#21]
**Describe the bug**
I imported a wallet using the openmask "import wallets" function. When filling in mnemonic, I followed the wrong format and it was imported successfully and show a account address('UQAlk84sY2w1ejWTOfuD0JqvGHgfKgkuVpv2vCaTfAdoNoCG').
like this:
word1
 word2
 word3
 word4
....
 word24

then ,I send some TON coins to this address. When I want to use this wallet to  send coins to other address , it prompts error “Request failed with status code 503”.
Then ,i used    "Reveal Secret Recovery Phrase" function to reveal my mnemonic.ITS a wrong format like i imported them!!!!! I cant use this mnemonic to import to other wallet APPs.
THEN , i try to fix format errors. like this "word1 word2 word3 ... word24",use this mnemonic to import to your OpenMask.The import was successful！ But another account address appeared.('UQDH1S8vPvARQpRueVThU31SKsAUo1w2TihYWT1ZOTc9mEkF')!!!!!!!!!!!!!!!!!!!!!!!When sending coins  , it prompts error “Request failed with status code 503” too.

i have no solution to take out my coins.       WHAT CAN I DO?

**Comment by KuznetsovNikita** [comment]
Hello @wozuizuilike 
Yesterday API provider was under high load, 
today it's become better, 
please try to withdraw your funds one more time

We will check import for different format with spaces and new lines

**Comment by onerdelrosario24** [comment]
hello sir, please help me, i cant send my money from openmask to gate io and also cant swap my other token from openmask

**Comment by HanueDev** [comment]
@onerdelrosario24 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by onerdelrosario24** [comment]
thank you

**Comment by Asisamee** [comment]
Delete

**Comment by Asisamee** [comment]
Delete

**Comment by onerdelrosario24** [comment]
hello , how to fix openmask transfers ?
