### ISSUE TITLE
Can not import wallet through mnemonics.

### ISSUE THREAD

**Issue by suyihao37** [OpenProduct/openmask-extension#23]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KuznetsovNikita** [comment]
Hello @suyihao37 
Yesterday API provider was under high load,
today it's become better, 
please try to import wallet one more time

thanks!
