### ISSUE TITLE
The problem with the transaction

### ISSUE THREAD

**Issue by Rusl-10** [OpenProduct/openmask-extension#24]
Hello! I made a transfer TON from my OpenMask (UQATkBnzb_XZR_Weni2C8BZ20E_188ndvsp_jglUVJf3DzPH) wallet to my Telegram wallet (UQDtyfGfQ7c408LbtiZXPx0b8g89PVkldl29eMV49SjV4YYs) I attach a screenshot that my TONY Telegram wallet is specified correctly! But for some reason, my 1.1865 TON went to another address, if you look in TON-explorer. Why did this happen? Who will refund my funds?
![1](https://github.com/OpenProduct/openmask-extension/assets/101989008/dba48332-34a1-4224-8a97-e8a4c76b7bb2)
![2](https://github.com/OpenProduct/openmask-extension/assets/101989008/41832b78-c40f-42ed-9f0f-d1d1ce97c73f)

**Comment by tranhung3010** [comment]
hi I shorted #Ton to the Mexc exchange but did not see any money on the exchange

**Comment by KuznetsovNikita** [comment]
Hello, thank you for report
Should be work correctly on 0.20.3 version

**Comment by KuznetsovNikita** [comment]
Please contact Mexc exchange support and provider the same information

Thank you
