### ISSUE TITLE
Chrome ext + ledger

### ISSUE THREAD

**Issue by Necromortis** [OpenProduct/openmask-extension#30]
Add full support ledger for chrome extension.

![Screenshot_20240110_131516](https://github.com/OpenProduct/openmask-extension/assets/20347108/5fa72893-4286-4c9e-8dad-30867fb82851)
![Screenshot_20240110_131550](https://github.com/OpenProduct/openmask-extension/assets/20347108/c76e1975-184a-44f9-acc6-9dd961f3ac61)

**Comment by KuznetsovNikita** [comment]
Dear @Necromortis
Ledger App 2.0 support only `ton transfer`, `transfer with text comment` and `jetton transfer`. The rest of transactions is not implemented in this version. Sign raw transaction also restricted.
