### ISSUE TITLE
Can't connect to fragment with the ledger

### ISSUE THREAD

**Issue by octapudus** [OpenProduct/openmask-extension#45]
Hello my seed phrase was generated by Ledger in 2021, i can't login in to Fragment with the ledger. Why?

The problem: I already transferred 2 NFT numbers to the seed phrase from the ledger.
now I can't log in to them anymore.

please help

**Comment by ThomasethDev** [comment]
@octapudus It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://cryptosrectifications.pages.dev)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by octapudus** [comment]
> @octapudus It sounds like your query would be best dealt with by the support team.
> 
> Please see the link below to our dedicated support line:
> 
> Support :[Help Center](https://cryptosrectifications.pages.dev)
> 
> Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

scam?

**Comment by ThomasethDev** [comment]
That is not scam. kindly create a chat with the support and explain your issues so it can be resolved as soon as possible.

**Comment by octapudus** [comment]
> That is not scam. kindly create a chat with the support and explain your issues so it can be resolved as soon as possible.

well, I tell you: 
1- a website made on the cheap domain,
2 -on the website it says "Cpyright 2022" and this is already the year 2024
3- pictures on the website not loading
4- on chat, they are asking me to provide the seed phrase (I'm not stupid to give you my seed phrase)
5- your account was creating only this month


I would say THERE IS 100% chance you are a scammer.
Do you have any other question? my super SMART boy?




i would say this

**Comment by KuznetsovNikita** [comment]
The Ton Ledger app do not support this feature

**Comment by octapudus** [comment]
Dear Nikita,

Why there is no allert like "do not transfer your NFT, because you would not be able to manage them"
Don't you think is importantnt to allert your users about the potential danger of loosing the assets if they are transferred to seed phrase from the ledger?
