### ISSUE TITLE
Add new DEX [Tegro.Finance] on TON to Wallet

### ISSUE THREAD

**Issue by DeFiTON** [OpenProduct/openmask-extension#7]
Good afternoon. Can add +1 more DEX on the TON blockchain to integration for your Wallet. Thanks!

Project site:
- https://tegro.finance/

Documentation and source code:
- https://github.com/orgs/TegroTON/repositories

- Roadmap and information:
https://tegro.gitbook.io/en/dex/

How to add a project? Integration Example, [DefiLllama](https://defillama.com/protocol/tegro-finance):
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/tegro/index.js

**Comment by KuznetsovNikita** [comment]
Dear @DeFiTON 

I will consider you offer as soon as you will support connection via OpenMask wallet.
Thank you

<img width="371" alt="Screenshot 2023-01-14 at 3 52 53" src="https://user-images.githubusercontent.com/22742808/212447589-7b5e1183-022f-4a25-8a3b-422db54ff5c6.png">

**Comment by KuznetsovNikita** [comment]
@DeFiTON 
<img width="422" alt="Screenshot 2023-01-28 at 11 58 37" src="https://user-images.githubusercontent.com/22742808/215262978-e5dd60a4-6f5d-4b4f-b88b-0b57cc385af1.png">
